### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by quasicomputational** [sol/stringbuilder#4]
The Semigroup-Monoid stuff is fixed in HEAD, but that hasn't been released yet, so this package's dependents are currently having to rely on head.hackage for 8.4 testing. Could a release be made, please?

**Comment by sol** [comment]
@quasicomputational Hey, thanks for bringing this up.  The version is already bumped and the release tagged, but for some reason it didn't make it to Hackage.  I'm not sure where I messed up.

**Comment by sol** [comment]
Duh.. Hackage rejects the package, this is why.

**Comment by sol** [comment]
Because of `-Werror` in the test suite, I think nonsensical, but well..

**Comment by sol** [comment]
Fixed! Thanks a lot!
